Search.appendIndex(
    [
                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Exceptions\\Exception",
            "name": "Exception",
            "summary": "Exception",
            "url": "classes/Pronamic-WordPress-Http-Exceptions-Exception.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Exceptions\\Exception\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020exception.",
            "url": "classes/Pronamic-WordPress-Http-Exceptions-Exception.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Exceptions\\Exception\u003A\u003Aget_request\u0028\u0029",
            "name": "get_request",
            "summary": "Get\u0020request.",
            "url": "classes/Pronamic-WordPress-Http-Exceptions-Exception.html#method_get_request"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Exceptions\\Exception\u003A\u003A\u0024request",
            "name": "request",
            "summary": "Request.",
            "url": "classes/Pronamic-WordPress-Http-Exceptions-Exception.html#property_request"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Facades\\Http",
            "name": "Http",
            "summary": "HTTP",
            "url": "classes/Pronamic-WordPress-Http-Facades-Http.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Facades\\Http\u003A\u003Aresult\u0028\u0029",
            "name": "result",
            "summary": "Result.",
            "url": "classes/Pronamic-WordPress-Http-Facades-Http.html#method_result"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Facades\\Http\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Request.",
            "url": "classes/Pronamic-WordPress-Http-Facades-Http.html#method_request"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Facades\\Http\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "GET.",
            "url": "classes/Pronamic-WordPress-Http-Facades-Http.html#method_get"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Facades\\Http\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "POST.",
            "url": "classes/Pronamic-WordPress-Http-Facades-Http.html#method_post"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Facades\\Http\u003A\u003Ahead\u0028\u0029",
            "name": "head",
            "summary": "HEAD.",
            "url": "classes/Pronamic-WordPress-Http-Facades-Http.html#method_head"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Facades\\Http\u003A\u003Afake\u0028\u0029",
            "name": "fake",
            "summary": "Fake.",
            "url": "classes/Pronamic-WordPress-Http-Facades-Http.html#method_fake"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Factory",
            "name": "Factory",
            "summary": "Factory",
            "url": "classes/Pronamic-WordPress-Http-Factory.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Factory\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "Instance.",
            "url": "classes/Pronamic-WordPress-Http-Factory.html#property_instance"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Factory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020factory.",
            "url": "classes/Pronamic-WordPress-Http-Factory.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Factory\u003A\u003Afake\u0028\u0029",
            "name": "fake",
            "summary": "Fake.",
            "url": "classes/Pronamic-WordPress-Http-Factory.html#method_fake"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Factory\u003A\u003Apre_http_request\u0028\u0029",
            "name": "pre_http_request",
            "summary": "Pre\u0020HTTP\u0020request",
            "url": "classes/Pronamic-WordPress-Http-Factory.html#method_pre_http_request"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Factory\u003A\u003A\u0024fakes",
            "name": "fakes",
            "summary": "Fakes.",
            "url": "classes/Pronamic-WordPress-Http-Factory.html#property_fakes"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Formatters\\CurlFormatter",
            "name": "CurlFormatter",
            "summary": "CURL\u0020formatter.",
            "url": "classes/Pronamic-WordPress-Http-Formatters-CurlFormatter.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Formatters\\CurlFormatter\u003A\u003Aformat\u0028\u0029",
            "name": "format",
            "summary": "Format.",
            "url": "classes/Pronamic-WordPress-Http-Formatters-CurlFormatter.html#method_format"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Formatters\\HttpieFormatter",
            "name": "HttpieFormatter",
            "summary": "HTTPie\u0020formatter.",
            "url": "classes/Pronamic-WordPress-Http-Formatters-HttpieFormatter.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Formatters\\HttpieFormatter\u003A\u003Aformat\u0028\u0029",
            "name": "format",
            "summary": "Format\u0020request.",
            "url": "classes/Pronamic-WordPress-Http-Formatters-HttpieFormatter.html#method_format"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Handler",
            "name": "Handler",
            "summary": "Handler",
            "url": "classes/Pronamic-WordPress-Http-Handler.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Handler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020handler.",
            "url": "classes/Pronamic-WordPress-Http-Handler.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Handler\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "Destruct.",
            "url": "classes/Pronamic-WordPress-Http-Handler.html#method___destruct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Handler\u003A\u003A\u0024url",
            "name": "url",
            "summary": "URL.",
            "url": "classes/Pronamic-WordPress-Http-Handler.html#property_url"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Handler\u003A\u003Amethod\u0028\u0029",
            "name": "method",
            "summary": "Method.",
            "url": "classes/Pronamic-WordPress-Http-Handler.html#method_method"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Handler\u003A\u003A\u0024args",
            "name": "args",
            "summary": "Arguments.",
            "url": "classes/Pronamic-WordPress-Http-Handler.html#property_args"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Handler\u003A\u003Ahttp_request_args\u0028\u0029",
            "name": "http_request_args",
            "summary": "HTTP\u0020request\u0020arguments\u0020filter.",
            "url": "classes/Pronamic-WordPress-Http-Handler.html#method_http_request_args"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Handler\u003A\u003A\u0024parsed_args",
            "name": "parsed_args",
            "summary": "Parsed\u0020arguments.",
            "url": "classes/Pronamic-WordPress-Http-Handler.html#property_parsed_args"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Request",
            "name": "Request",
            "summary": "HTTP\u0020Request",
            "url": "classes/Pronamic-WordPress-Http-Request.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Request\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020request.",
            "url": "classes/Pronamic-WordPress-Http-Request.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Request\u003A\u003A\u0024method",
            "name": "method",
            "summary": "Method.",
            "url": "classes/Pronamic-WordPress-Http-Request.html#property_method"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Request\u003A\u003A\u0024url",
            "name": "url",
            "summary": "URL\u0020to\u0020retrieve.",
            "url": "classes/Pronamic-WordPress-Http-Request.html#property_url"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Request\u003A\u003A\u0024args",
            "name": "args",
            "summary": "Request\u0020arguments.",
            "url": "classes/Pronamic-WordPress-Http-Request.html#property_args"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Request\u003A\u003Aheaders\u0028\u0029",
            "name": "headers",
            "summary": "Headers.",
            "url": "classes/Pronamic-WordPress-Http-Request.html#method_headers"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Request\u003A\u003Abody\u0028\u0029",
            "name": "body",
            "summary": "Body.",
            "url": "classes/Pronamic-WordPress-Http-Request.html#method_body"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Request\u003A\u003Aas_curl\u0028\u0029",
            "name": "as_curl",
            "summary": "As\u0020cURL.",
            "url": "classes/Pronamic-WordPress-Http-Request.html#method_as_curl"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Request\u003A\u003Aas_httpie\u0028\u0029",
            "name": "as_httpie",
            "summary": "AS\u0020HTTPie.",
            "url": "classes/Pronamic-WordPress-Http-Request.html#method_as_httpie"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Request\u003A\u003Afrom_args\u0028\u0029",
            "name": "from_args",
            "summary": "Create\u0020request\u0020object\u0020from\u0020WordPress\u0020request\u0020arguments\u0020array.",
            "url": "classes/Pronamic-WordPress-Http-Request.html#method_from_args"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Response",
            "name": "Response",
            "summary": "HTTP\u0020Response",
            "url": "classes/Pronamic-WordPress-Http-Response.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Response\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020response\u0020array.",
            "url": "classes/Pronamic-WordPress-Http-Response.html#method___construct"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Response\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "Status.",
            "url": "classes/Pronamic-WordPress-Http-Response.html#method_status"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Response\u003A\u003Amessage\u0028\u0029",
            "name": "message",
            "summary": "Message.",
            "url": "classes/Pronamic-WordPress-Http-Response.html#method_message"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Response\u003A\u003Abody\u0028\u0029",
            "name": "body",
            "summary": "Body.",
            "url": "classes/Pronamic-WordPress-Http-Response.html#method_body"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Response\u003A\u003Ajson\u0028\u0029",
            "name": "json",
            "summary": "JSON.",
            "url": "classes/Pronamic-WordPress-Http-Response.html#method_json"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Response\u003A\u003Asimplexml\u0028\u0029",
            "name": "simplexml",
            "summary": "SimpleXML.",
            "url": "classes/Pronamic-WordPress-Http-Response.html#method_simplexml"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Response\u003A\u003Aget_array\u0028\u0029",
            "name": "get_array",
            "summary": "Get\u0020array.",
            "url": "classes/Pronamic-WordPress-Http-Response.html#method_get_array"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Response\u003A\u003Aarray_from_file\u0028\u0029",
            "name": "array_from_file",
            "summary": "From\u0020file.",
            "url": "classes/Pronamic-WordPress-Http-Response.html#method_array_from_file"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Response\u003A\u003A\u0024array",
            "name": "array",
            "summary": "Remote\u0020request\u0020response\u0020array.",
            "url": "classes/Pronamic-WordPress-Http-Response.html#property_array"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/pronamic-wordpress-http-exceptions.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Facades",
            "name": "Facades",
            "summary": "",
            "url": "namespaces/pronamic-wordpress-http-facades.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/pronamic-wordpress-http.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress",
            "name": "WordPress",
            "summary": "",
            "url": "namespaces/pronamic-wordpress.html"
        },                {
            "fqsen": "\\Pronamic",
            "name": "Pronamic",
            "summary": "",
            "url": "namespaces/pronamic.html"
        },                {
            "fqsen": "\\Pronamic\\WordPress\\Http\\Formatters",
            "name": "Formatters",
            "summary": "",
            "url": "namespaces/pronamic-wordpress-http-formatters.html"
        }            ]
);
